- name: Setup service {{name}}
  become: true
  block:
    - name: Copy {{src}} to {{dest}}
      ansible.builtin.copy:
        src: "{{src}}"
        dest: "{{dest}}"

    - name: Link {{name}} service
      ansible.builtin.command: sudo /usr/bin/systemctl enable {{servicefile}}

    - name: Stop {{name}} service
      async: 180
      poll: 5
      ansible.builtin.systemd:
        name: "{{name}}"
        state: stopped

    - name: Reload daemon
      ansible.builtin.command: sudo /usr/bin/systemctl daemon-reload

    - name: Start {{name}} service
      ansible.builtin.command: sudo /usr/bin/systemctl start {{name}}

