- name: Create user
  become: true
  ansible.builtin.user:
    name: "{{username}}"
    groups: "docker"  # The name group gets added automatically
      
- name: Create directory
  become: true
  ansible.builtin.file:
    path: "{{dest_path}}"
    state: directory
    owner: "{{username}}"
    group: "{{username}}"
